### PR TITLE
Add Battleground and Savanna pictures

### PR DESCRIPTION
**Pull request by ccomrade**
- `Levels/Multiplayer/IA/Battleground`
- `Levels/Multiplayer/IA/Savanna`

### CODE REVIEW

**Comment by tuunsalat** [comment]
Please add img for Levels/Multiplayer/PS/Tremor
Or how can I add it?

**Comment by diznq** [comment]
@tuunsalat could you send us the picture here by attaching it in a comment? I could add it then

**Comment by tuunsalat** [comment]
> @tuunsalat could you send us the picture here by attaching it in a comment? I could add it then

Yes. Which img resolution do you need?
Here is one at 900 x 506
tremor_crymp

**Comment by diznq** [comment]
Thank you, I added it

**Comment by tuunsalat** [comment]
And here is one for Frost map
frost

**Comment by diznq** [comment]
> Hi @diznq can you add this pic (to serverlist page) for map "Farm" please? ;) farm

What is the map path: multiplayer/ps/...?

**Comment by tuunsalat** [comment]
> > Hi @diznq can you add this pic (to serverlist page) for map "Farm" please? ;) farm
> 
> What is the map path: multiplayer/ps/...?

Yes PS

**Comment by tuunsalat** [comment]
@diznq 
Please update Levels/Multiplayer/PS/Farm/ to use this img
Thank you :)
farm_crymp2

**Comment by tuunsalat** [comment]
@diznq
Ok it was "fun" to try some weather/colors.. but Farm should look like this instead. This is the final
Can you update the img on crymp serverlist please? Make sure it loads the new one (not the old from cache if same filename)
Thank you :)
farm_crymp3

**Pull request merged**
